import Head from 'next/head'
import { useEffect, useState } from 'react'
import axios from 'axios'
import SearchForm from '../src/components/SearchForm'
import CardList from '../src/components/CardList'

export default function Home() {
  const [data, setData] = useState([])
  const [filterParam, setFilterParam] = useState('')
  const [filteredData, setFilteredData] = useState(data)

  async function getData() {
    try {
      const response = await axios.get('https://swapi.dev/api/people')
      setData(response.data.results)
    } catch (error) {
      console.error(error)
    }
  }

  const filterData = () => {
    const filteredData = data.filter((person) => {
      return person.name.includes(filterParam)
    })

    return filteredData
  }

  useEffect(() => {
    getData()
  }, [])

  useEffect(() => {
    setFilteredData(filterData())
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data, filterParam])

  return (
    <div>
      <Head>
        <title>Calendar</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='container'>
        <SearchForm filterParam={filterParam} setFilterParam={setFilterParam} />
        <CardList data={filteredData} />
      </main>
    </div>
  )
}
